twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_3_layout.html.twig']
    globals:
        available_locales: '%available_locales%'

when@test:
    twig:
        strict_variables: true
