services:
    # ----------------------------------------------
    # Helper
    # ----------------------------------------------
    app.helper.pagination:
        class: AppBundle\Helper\PaginationHelper
