services:
    # ----------------------------------------------
    # Helper
    # ----------------------------------------------
    app.helper.pagination:
        class: AppBundle\Helper\PaginationHelper
    # ----------------------------------------------------------
    # Validator
    # ----------------------------------------------------------
    app.validator.unique_code_value:
        class: AppBundle\Validator\Constraints\UniqueCodeValueValidator
        arguments:
            - '@doctrine.orm.default_entity_manager'
        tags:
            - { name: validator.constraint_validator }
